### ISSUE TITLE
Can We give Name of the Employee Associated Document List

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#101]
It Will become more easy for the user to have a glance Directly

![documentemployeename](https://cloud.githubusercontent.com/assets/7089705/3872970/4a292188-2127-11e4-9345-dd88dd471d2d.png)

**Comment by r2international** [comment]
we don't provide documents grid in default(initial page loaded), user has to select employee and document type to get the documents grid :)
