### ISSUE TITLE
Empty grid no need to present

### ISSUE THREAD

**Issue by r2international** [rameshbolla/LTMS#11]
If no records available for a grid to show, then we don't need grid just give a nice message to user that no records available.

![label2](https://cloud.githubusercontent.com/assets/4068693/3778514/96de66e2-1974-11e4-8c99-b918c3872f05.png)

**Comment by AbhirajSharan** [comment]
@r2international  Issue still persisting as it is showing this following error
![leaverequestissuereopen](https://cloud.githubusercontent.com/assets/7089705/3854188/7bf0c4e2-1ed3-11e4-8378-f10176a4a1c2.png)
