### ISSUE TITLE
Team leaves=> Add

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#111]
Once Particular team holiday added should not show in the check box to avoid the duplicate entry. We can think about it in Future
![teamholidaycheckbox](https://cloud.githubusercontent.com/assets/7089705/3876453/35c169e6-215c-11e4-9426-4d99bfd67537.png)

**Comment by r2international** [comment]
@AbhirajSharan  this is updated according to new requirement, add/update is same screen.

**Comment by AbhirajSharan** [comment]
@r2international :closed #111
