### ISSUE TITLE
Deleted History Recover Toaster Message should show some recover successfull message

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#115]
![deletedhistorytoastermessage](https://cloud.githubusercontent.com/assets/7089705/3876854/519ce510-2160-11e4-9b22-cbcb08a76686.png)

**Comment by r2international** [comment]
@AbhirajSharan  working fine but showing alert message

![error](https://cloud.githubusercontent.com/assets/4068693/3948554/bf6dc6e8-26a8-11e4-8bec-6cc7a95509c4.png)

**Comment by AbhirajSharan** [comment]
Working Fine
