### ISSUE TITLE
apply leave issue.

### ISSUE THREAD

**Issue by r2international** [rameshbolla/LTMS#12]
When user try to apply for a leave, leave popup automatically opens calendar control to select date.

![label2](https://cloud.githubusercontent.com/assets/4068693/3778534/e587c9be-1974-11e4-97c0-711e1fcf3dad.png)

this is makes user uneasy with application, we need to change calendar should show when user clicks in textbox or separate icon to open calendar.

**Comment by AbhirajSharan** [comment]
@r2international  Issue still persisting in Employee Module also the list of Leave Applied not showing in particular Module as well as SuperAdmin Module
![employeeleavedatepicker](https://cloud.githubusercontent.com/assets/7089705/3873465/9355b984-2131-11e4-8fb0-a6ea8d384cc1.png)

**Comment by AbhirajSharan** [comment]
@r2international  In Chrome browser it is showing with blue border,but  it is working fine with fire fox
![chromeapplyleave](https://cloud.githubusercontent.com/assets/7089705/3887696/ae027df2-21f5-11e4-86a7-19e8cbf0008f.png)

**Comment by AbhirajSharan** [comment]
its working Fine
