### ISSUE TITLE
Empty grid no need to present : throughout the applicaiton

### ISSUE THREAD

**Issue by r2international** [rameshbolla/LTMS#125]
we have working model code for this bug, "ApplyLeaveList.cshtml"

accordingly we need to check each grid view then update. 

mention list of files updated in comment

**Comment by AbhirajSharan** [comment]
@r2international : Implemented in following :- CEOAbsentList, CeoEmployeeList ,  CeoHolidayList,  Ceolatenesslist  ,CeoTeamEmployeeLeavesList, CeoTeamLeavesDetailsList, EmployeeWiseLatenesslist,_HrLatenessList, EmployeeList, HrLatenessList,
LatenessList,AdminLatenessList,AdminleaveList,DocumentList,HrSalarylist,CalendarYearList
,DesignationList,DivisionList,DocumentTypeList,EmployeeBankAccountList,LeaveStatusTypeList,
LeaveTypeList,TeamsList,TerminationTypeList,UserRolesList,EmployeeAdminLatenessList,HolidaysList,TeamEmployeeLeavesList,TeamLeavesDetailsList,ApplyleaveList,ApprovedHistoryList,
LeaveapprovalList,ManagerTeamList,Officeloclist,CountryCodeList,FullSetlementList,NoticeServeList,
PfSettlementList,TerminationList,UsersList

**Comment by r2international** [comment]
@AbhirajSharan  following grids also need to have

EmergencyContactlist.cshtml
EmployeeHolidaysList.cshtml
EntitlementEmployeeList.cshtml
EntitlementList.cshtml
PersonalEntitlementList.cshtml
PersonalHolidaysList.html
Assignleavelist.cshtml
DeletedEmployeeList.cshtml
DeletedHolidayList.cshtml
DeletedLatenessList.cshtml
DeletedLeaveList.cshtml

**Comment by r2international** [comment]
hoping all are updated.
