### ISSUE TITLE
By Clicking two tabs Simultaneously whole UI is disappearing the Text 

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#13]

**Comment by AbhirajSharan** [comment]
![error](https://cloud.githubusercontent.com/assets/7089705/3778736/9d7a00b6-1978-11e4-9fcb-244e0b7d285e.png)

**Comment by r2international** [comment]
@AbhirajSharan  try to re produce this issue, if it appears again let me know
