### ISSUE TITLE
Ceo AbsentList Status and Leave Type missing

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#131]
![ceoabsentlist](https://cloud.githubusercontent.com/assets/7089705/3950469/9f1c57d4-26c5-11e4-8e5c-31277564da2d.png)

**Comment by r2international** [comment]
@AbhirajSharan we show only approved list here, so no need to present status &  we need to change grid fields like following

Name Fromdate Todate Message appliedOn ApprovedBy(manager) leavetype

it should be having much meaningful & easy to understand. :+1:

**Comment by AbhirajSharan** [comment]
We can close the issue as the requirement has changed.
