### ISSUE TITLE
Ceo Lateness List we can remove created by and created on 

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#135]
![ceolatenesslistfields](https://cloud.githubusercontent.com/assets/7089705/3950912/dee097c4-26cd-11e4-8f14-8f8639ffcf57.png)

**Comment by r2international** [comment]
@AbhirajSharan  we have enough space let it be no problem, we need to present reason message in better way.

**Comment by r2international** [comment]
@AbhirajSharan  Employeewise lateness also should update
