### ISSUE TITLE
apply leave: restrict user not to take morethan 3 weeks

### ISSUE THREAD

**Issue by r2international** [rameshbolla/LTMS#148]
user should not take/apply more than 3 weeks

**Comment by AbhirajSharan** [comment]
@r2international It is allowing user to take leaves more than 3 weeks .
![employeeleaverange](https://cloud.githubusercontent.com/assets/7089705/4182869/f21deee6-3734-11e4-9c6f-82dfb873ad5e.png)

**Comment by AbhirajSharan** [comment]
@r2international  Closed #148
