### ISSUE TITLE
employee salary details grid

### ISSUE THREAD

**Issue by r2international** [rameshbolla/LTMS#16]
refer #11 

![label2](https://cloud.githubusercontent.com/assets/4068693/3778896/45de8a5e-197b-11e4-8be3-f6749fc2847d.png)

**Comment by AbhirajSharan** [comment]
@r2international  Issue still persisting ,I have checked in Employee Account but it seems still the same also we can implement in Leave Entitlement
![employeesalaryreopen](https://cloud.githubusercontent.com/assets/7089705/3854120/5a117a0c-1ed2-11e4-97fc-f1d603ffb33c.png)
