### ISSUE TITLE
Hr Document After save not reflecting In grid(Document list)

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#162]
![hrdocumentgrid](https://cloud.githubusercontent.com/assets/7089705/4062183/08efcba2-2dfe-11e4-8b5e-2473348a56fd.png)

**Comment by r2international** [comment]
user has to select search criteria to see relevant documents, no default list to be provided.

**Comment by AbhirajSharan** [comment]
@r2international  closed #162
