### ISSUE TITLE
Notice serve date picker issue

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#166]
![noticeservedatepicker](https://cloud.githubusercontent.com/assets/7089705/4115353/f080c8b4-3276-11e4-8ef7-817bcce67c4b.png)

**Comment by r2international** [comment]
@AbhirajSharan  whats the issue here ? describe.

**Comment by AbhirajSharan** [comment]
@r2international :when we click on Edit Notice serve End Date date picker pops out by default .

**Comment by AbhirajSharan** [comment]
@r2international Still reflecting the same #166

**Comment by AbhirajSharan** [comment]
@r2international closed #166
