### ISSUE TITLE
apply leave: past leaves can not editable

### ISSUE THREAD

**Issue by r2international** [rameshbolla/LTMS#170]
once a leave approved and happened, user can't update any details to that leave.

**Comment by AbhirajSharan** [comment]
@r2international : When from Hr Module we are approving the leave ,it reflects Unknown status in Employee side.So unable to perform the operation as status is not showing relevant data.

![employeemoduleleavegrid](https://cloud.githubusercontent.com/assets/7089705/4182373/5fe63bc0-372d-11e4-9674-e9463cd341c1.png)

**Comment by r2international** [comment]
@AbhirajSharan  this is different bug, we are on the way to complete.

**Comment by AbhirajSharan** [comment]
@r2international  : we can close this bug ,as the Leave Approval section removed from HR Module
