### ISSUE TITLE
Add Team with validation is not fitting into the screen . 

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#174]
![addteamvalidation](https://cloud.githubusercontent.com/assets/7089705/4133409/23b763a4-335e-11e4-8c55-22f7423a9b9a.png)

**Comment by r2international** [comment]
@AbhirajSharan  i guess this can fit now, we trimmed validation message to "required".

**Comment by AbhirajSharan** [comment]
@r2international :closed #174
