### ISSUE TITLE
Hr Module session issue in Google chrome

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#175]
![hrmodulesessiontimeout](https://cloud.githubusercontent.com/assets/7089705/4133465/f48b4b8a-335e-11e4-9b85-25b93b6b5627.png)

**Comment by r2international** [comment]
@AbhirajSharan  this will not happen if we check session timing in script before do production

**Comment by AbhirajSharan** [comment]
@r2international  : closed #175
