### ISSUE TITLE
Hr Module Leave History Search and Clear button not working.

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#181]
![leavehistorysearchnotworking](https://cloud.githubusercontent.com/assets/7089705/4161273/267a8e22-34cb-11e4-8081-146cfacd2665.png)

**Comment by r2international** [comment]
"Clear" button for this search criteria not necessarily required.

**Comment by AbhirajSharan** [comment]
@r2international  :closed #181
