### ISSUE TITLE
HR Module Assign Leave Edit date Picker Issue.

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#183]
HR Module Assign Leave Edit date Picker Issue.when we click on Edit by default the date picker calender opens
![hrmoduleassignleaveedit](https://cloud.githubusercontent.com/assets/7089705/4181847/92e6e678-3723-11e4-8790-ee46dfd779df.png)

**Comment by r2international** [comment]
this is updated with latest plan

**Comment by AbhirajSharan** [comment]
@r2international  Closed #183
