### ISSUE TITLE
In manager Module leave approval grid  message view is overlapping into other field.

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#199]
![managermoduleleavemessage](https://cloud.githubusercontent.com/assets/7089705/4216257/96c012b4-38d7-11e4-8a10-d2e1fb500e0d.png)

**Comment by r2international** [comment]
@AbhirajSharan  we never get this type of messages from employee. any word not more than 15 letters length, but you tested with 40 letters word.
