### ISSUE TITLE
As we are approving Leave directly from Manager we need to remove status from Hr Edit Leave

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#208]
![hrleavestatus leavetype](https://cloud.githubusercontent.com/assets/7089705/4235449/738e123a-39bf-11e4-9e85-76a56a86dc46.png)

**Comment by r2international** [comment]
this is updated according to latest requirement

**Comment by AbhirajSharan** [comment]
@r2international  closed #208
