### ISSUE TITLE
Need to handle this kind of situation For Entire Date Picker.

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#210]
Suppose we have given year limit as 2015 , It will not allow to select 2016,when we select the next button after December  month 2015 it showing the date picker year as 2014 as we have two year range but when we select any date it is showing date of 2016 , so it will allow user to select the date out of the year range. Need to handle for the Entire date picker.
![datepickerdateafterthelimityear](https://cloud.githubusercontent.com/assets/7089705/4236120/d79779e2-39c4-11e4-8850-c8c10ce7b040.png)
![datepickerdateissue](https://cloud.githubusercontent.com/assets/7089705/4236159/0ec1ed58-39c5-11e4-8e21-cb75bcfbab6e.png)

**Comment by r2international** [comment]
@AbhirajSharan  very good, this is interesting issue :+1: 

We don't properly handle dependency between start and end dates, will rectify this soon.

**Comment by r2international** [comment]
fix has done on actual leave application from employee

**Comment by AbhirajSharan** [comment]
@r2international still pending in Salary ,Notice Serve etc

**Comment by r2international** [comment]
@AbhirajSharan  mention all the places need to add this logic, i will directly go and fix :+1:

**Comment by AbhirajSharan** [comment]
@r2international  In some places such as add notice and Termination issue still persist

**Comment by AbhirajSharan** [comment]
@r2international  Issue still persisting in Final Settlement.

**Comment by AbhirajSharan** [comment]
@r2international Closed #210
