### ISSUE TITLE
Hr Module Team member wise  leaves Issue

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#211]
Initially we visit the page, the page shows 0 records but when we click on clear button it shows the list of all records.when we click on clear button it should also show the 0 records ,the concept of clear button is to refresh it and show as it was showing when we visited the page.Either we need to show all records when we visit the page first time or after the click event of clear button should show zero numbers of records.Both the scenarios should match with each other.

![teammembersinitially](https://cloud.githubusercontent.com/assets/7089705/4246299/5f5ed28e-3a48-11e4-95bd-95419fa24df8.png)

![teammembersafterclearbutton](https://cloud.githubusercontent.com/assets/7089705/4246306/87b7ba0c-3a48-11e4-80b7-be0a5d3b50cc.png)

**Comment by r2international** [comment]
clear button removed, based on user search condition we show list.

**Comment by AbhirajSharan** [comment]
@r2international  Closed #211
