### ISSUE TITLE
CEO Lateness List Year Dropdown

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#218]
In CEO lateness list Date picker year drop down is taking 2015 also ,we can restrict user
 to see till today's date ,to show date after Today's Date is irrelevant.

![ceolatenessdatepicker](https://cloud.githubusercontent.com/assets/7089705/4267816/5e348dce-3ca3-11e4-986e-1cb0f84477a1.png)

**Comment by r2international** [comment]
this is updated according to new requirement

**Comment by AbhirajSharan** [comment]
@r2international  Closed #218
