### ISSUE TITLE
SuperAdmin Add Emergency Contact Saving 4 similar Records at One save Event

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#22]
![superadminemergencycontact](https://cloud.githubusercontent.com/assets/7089705/3793894/2434e9dc-1ba3-11e4-91ee-0f171d92fd31.png)

**Comment by r2international** [comment]
@AbhirajSharan  I tried in both firefox & chrome, i don't see this error. how to reproduce this ?

**Comment by AbhirajSharan** [comment]
@r2international  I have checked now the problem is not persisting but in previous version of the Production it was showing the following Error
