### ISSUE TITLE
CEO Lateness list date picker Increment is allowing to pick the weekend.

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#222]
In Ceo lateness date picker ,when we increment date with increment icon it is allowing to select the weekend also.
![ceolatenesslistdatepickerincrement](https://cloud.githubusercontent.com/assets/7089705/4268381/b00a45da-3cad-11e4-9ddd-4e0ede6157e3.png)

**Comment by r2international** [comment]
with latest functionality, we don't have this issue

**Comment by AbhirajSharan** [comment]
@r2international  Closed #222
