### ISSUE TITLE
Manager Module absent Search Date picker Issue.

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#235]
We should not restrict manager to see only three month Absentees list.
![managerabsentdatepickerrestriction](https://cloud.githubusercontent.com/assets/7089705/4332494/ae957970-3fd4-11e4-9621-4a412bd3f7ca.png)

**Comment by r2international** [comment]
@AbhirajSharan  that's fine, they will let us know if they need
