### ISSUE TITLE
CEO Absent History should have Month Search Option

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#264]
We need to have combination of Employee + Year + Month Search as it will provide more Refine Search 

![ceoabsenthistorymonth](https://cloud.githubusercontent.com/assets/7089705/4417213/5c7d42ae-4550-11e4-9554-a32fa069f55d.png)

**Comment by r2international** [comment]
@AbhirajSharan  guess, if taz want to see your last year total leaves taken ?
