### ISSUE TITLE
disable save button once user clicks(avoid multiple clicks, duplicate entries).

### ISSUE THREAD

**Issue by r2international** [rameshbolla/LTMS#296]
possible places, where user gives input data that may take significant time.

**Comment by r2international** [comment]
need to check following actions are working with 
1. apply leave
2. edit leave
3. create account
4. edit account
5. add lateness
6. edit lateness
7. quick lateness
8. quick lateness(save & close)
9. add absents(SA, TL, Manager, HR)

**Comment by AbhirajSharan** [comment]
@r2international  Closed #296
