### ISSUE TITLE
lateness exactly one hour should add & message also should be meaningful

### ISSUE THREAD

**Issue by r2international** [rameshbolla/LTMS#319]
minutes are mandatory, but any employee comes exactly one hour late then ?

need to test for singler or plural for minutes and hours

**Comment by r2international** [comment]
@AbhirajSharan  test below pattern

public static string LateMessage(int? hours, int? min)
    {
        string result = "";
        if (hours == 0 || hours == null)
        {
            if (min == 0)
                return " :) ";
            else if (min == 1)
                result = min.ToString() + " min";
            else
                result = min.ToString() + " mins";
            return result;
        }
        else
        {
            if (hours == 1)
                result = hours.ToString() + " Hour ";
            else
                result = hours.ToString() + " Hours ";
            if (min == 0 || min == null)
                return result;
            else if (min == 1)
                return (result + min.ToString() + " min");
            else
                return (result + min.ToString() + " mins");
        }
    }

**Comment by AbhirajSharan** [comment]
@r2international Closed#319
