### ISSUE TITLE
disable save button once user clicks(missing some places)

### ISSUE THREAD

**Issue by r2international** [rameshbolla/LTMS#325]
following list need to update

**Comment by r2international** [comment]
list below to test
1. team adding/updating
2. team deleting confirmation dialog
3. division adding/updating
4. division deleting confirmation dialog
5. termination type adding/updating
6. document type adding/updating
7. document type delete confirmation dialog
8. designation adding/updating
9. designation delete confirmation dialog
10. calendar year adding
11. calendar year editing confirmation dialog
12. location adding/updating
13. location deleting confirmation dialog
14. country code adding
15. country code delete confirmation dialog
16. emergency contact details adding/updating
17. delete emergency contact details confirmation dialog
18. add multiple team leaves saving
19. update lateness message by employee

**Comment by AbhirajSharan** [comment]
@r2international  Closed#325
