### ISSUE TITLE
Hr Leave History Add Leave->Save--> showing Details Tab Header

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#34]
![hrleavehistoryapplyleave](https://cloud.githubusercontent.com/assets/7089705/3796336/b8661508-1bc7-11e4-8176-435602b0d1a4.png)

**Comment by r2international** [comment]
@AbhirajSharan  how to reproduce this error. provide browser & version

**Comment by AbhirajSharan** [comment]
@r2international  You Can check  this Error on Google Chrome steps are following ->Admin =>Click on Quick Lateness =>Save Jquery Dialogue. Actually this is not a browser compatibility Issue its a Bug.Based on the requirement after clicking on save button Jquery Dialogue needs to be open and should be refreshed with blank fields when data is saved.

**Comment by AbhirajSharan** [comment]
@r2international  closed #34
