### ISSUE TITLE
Details Location Name is showing deleted List also in dropdown

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#43]
![detailslocationname](https://cloud.githubusercontent.com/assets/7089705/3823413/584e1706-1d39-11e4-89c1-808859aea94f.png)

**Comment by r2international** [comment]
@AbhirajSharan  official details already placed in first information, no need this section

**Comment by AbhirajSharan** [comment]
@ramesh Some of the Fields moved to section 1 but still there are some fields which needs to be shown on the official details section as it is showing any where else

**Comment by r2international** [comment]
@AbhirajSharan  we are showing divsion in section 1, personal email we are not capturing & location is "HR can see only his/her" location employee details only.

if you need any other details add a fresh bug/feature :+1:

**Comment by AbhirajSharan** [comment]
We are not showing location name rt now in our present application as our requirement changed.so at this point of time we can close this issue
