### ISSUE TITLE
Official Details UI issue

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#47]
![officialdetailsui](https://cloud.githubusercontent.com/assets/7089705/3823870/3944d8f8-1d3f-11e4-836b-0299d2041803.png)

**Comment by r2international** [comment]
@AbhirajSharan  section removed.

**Comment by r2international** [comment]
@AbhirajSharan  add a suggestion if we need to show removed section details in some other sections.

**Comment by AbhirajSharan** [comment]
@r2international  : I think we can add it in Employee first Information which is Section 1.The removed section is only editable by the Hr ..so ,it will be better to put in section 1 as we are not providing Edit option in first section

**Comment by r2international** [comment]
#43 same applies here too :+1:

**Comment by AbhirajSharan** [comment]
We are not showing location name rt now in our present application as our requirement changed.so at this point of time we can close this issue
