### ISSUE TITLE
Mobile as well as Telephone is taking more digits than Required ..Need to have masking on these fields

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#48]
![telephonenumber](https://cloud.githubusercontent.com/assets/7089705/3823981/d148c5c8-1d40-11e4-86ed-9bf825275fee.png)

**Comment by AbhirajSharan** [comment]
@r2international  Mobile and Telephone not following masking continues on taking more digits then required.
![mobilemaskingissue](https://cloud.githubusercontent.com/assets/7089705/3853910/a29f7f2a-1ece-11e4-9c26-1b369b55407e.png)

**Comment by r2international** [comment]
mobile is always 10 digits & work telephone is 8 to 12 digits & work telephone is not mandatory

**Comment by AbhirajSharan** [comment]
@r2international  closed #48
