### ISSUE TITLE
While Clicking on official Details Edit or Contact Details Edit Jquery UI dailog 

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#49]
While Clicking to these Edit buttons ..it is showing half of details on the screen ..user needs to scroll down to check the details
![dailoguidisplayissue](https://cloud.githubusercontent.com/assets/7089705/3824039/cb5d692e-1d41-11e4-8ba3-3d5c96315745.png)

**Comment by r2international** [comment]
@AbhirajSharan  let user do that.
