### ISSUE TITLE
Hr Add Leave Auto Search is working but not allowing to select the Employee

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#50]
![addleaveautosearch](https://cloud.githubusercontent.com/assets/7089705/3826170/fe26c30c-1d5d-11e4-9b47-1c5a86ebf505.png)

**Comment by r2international** [comment]
@AbhirajSharan  this one will chage with latest considerations.

**Comment by r2international** [comment]
this is update according to new requirement, go to absents then add absent for this action

**Comment by AbhirajSharan** [comment]
@r2international  closed #50
