### ISSUE TITLE
After Uploading the files it is not reflecting In Grid

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#56]
![uploadfilesgridissue](https://cloud.githubusercontent.com/assets/7089705/3827154/dc90f818-1d6a-11e4-8beb-92edb1d5f47b.png)

**Comment by r2international** [comment]
@AbhirajSharan documents grid shows list on user demand. i.e we will not show default grid, user has to select employee & file type to see available documents.

**Comment by AbhirajSharan** [comment]
As described by you we can close this issue
