### ISSUE TITLE
Calender Year Date Picker is showing Only 2 Years Date Range

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#57]
![calenderyeardaterange](https://cloud.githubusercontent.com/assets/7089705/3827327/041acf06-1d6d-11e4-8a92-c30d47371775.png)

**Comment by r2international** [comment]
@AbhirajSharan  yes, you can setup calendar year for current year or next year but not previous years(or next next year).

**Comment by AbhirajSharan** [comment]
We can close this if it is a human error which leads to Invalid Bug
