### ISSUE TITLE
Data Irrelevant as a user because there is no option in date picker for 2012,2011,2013

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#58]
![datairrelevant](https://cloud.githubusercontent.com/assets/7089705/3828185/931f5ed0-1d75-11e4-9e97-6d30167c5e04.png)

**Comment by AbhirajSharan** [comment]
@r2international  with your Reference #57 .We need to test as a User not as a developer so why the  data in the above showing date as 2011,2012,2013 in the grid.

**Comment by r2international** [comment]
@AbhirajSharan  thats the human error, for testing purpose i entered in database directly.

**Comment by AbhirajSharan** [comment]
As the data is not coming  directly from the application ..It is enter directly on data base we can close this bug
