### ISSUE TITLE
Holidays list error

### ISSUE THREAD

**Issue by r2international** [rameshbolla/LTMS#6]
when we setup system with initial details, list of holidays showing an error message.

![holidayserror](https://cloud.githubusercontent.com/assets/4068693/3778255/7ce37fc4-1970-11e4-871e-545e658e3c36.png)

If no details available, we need to show empty grids.

**Comment by AbhirajSharan** [comment]
@r2international  Holidays List still showing the same Error in Employee Module

**Comment by AbhirajSharan** [comment]
@r2international  I am Closing ,It is working fine now
