### ISSUE TITLE
Final Settlement Edit File should show the previous file name

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#62]
Final Settlement Edit File should show the previous file name but showing no file choosen
![finalsettlementeditfile](https://cloud.githubusercontent.com/assets/7089705/3838119/002082e2-1dfe-11e4-9e89-b7e7ff11638d.png)

**Comment by r2international** [comment]
@AbhirajSharan we don't need to show file name, what is the use to user ? if there is any change in scan copy he/she can upload new one. We don't update scan copy with empty file just like how we update employee details(with photo or without photo attachment ...!)

**Comment by AbhirajSharan** [comment]
We can close this bug as justified
