### ISSUE TITLE
Final Settlement Cheque Issue

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#69]
while adding the final settlement if the cheque field is left blank .when we go once for the edit of the final settlement it is now allowing to save data
![finalsettlementcheque](https://cloud.githubusercontent.com/assets/7089705/3838672/098ebc78-1e07-11e4-82fa-4ff0cf1c61c5.png)

**Comment by r2international** [comment]
@AbhirajSharan  its good to update scan copy if he/she forgot to add while adding initially.

**Comment by AbhirajSharan** [comment]
Working Fine
