### ISSUE TITLE
label change for leave entitlement

### ISSUE THREAD

**Issue by r2international** [rameshbolla/LTMS#7]
need to change below title to just entitlement

![-_ltms_application_-_2014-08-01_17 10 28](https://cloud.githubusercontent.com/assets/4068693/3778330/d89a5fb8-1970-11e4-8198-316041543f39.png)

**Comment by r2international** [comment]
leave entitlement is more meaningful :+1:

**Comment by AbhirajSharan** [comment]
@r2international  : Label Name still showing the same Name ie. Employee Entitlement

**Comment by AbhirajSharan** [comment]
this is working fine
