### ISSUE TITLE
Adding Team Leaves clicking on Save showing this message

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#73]
![teamleavesaftersave](https://cloud.githubusercontent.com/assets/7089705/3839242/6650b91e-1e0e-11e4-9237-3250ee41d7ff.png)

**Comment by r2international** [comment]
@AbhirajSharan  with latest leaves logic(1.25 OR 1.5), we need to rework through entire leaves section.

**Comment by AbhirajSharan** [comment]
@r2international Issue still persisting.
![addingteamleaves](https://cloud.githubusercontent.com/assets/7089705/4646598/a40f6592-5474-11e4-9686-260d69234621.png)

**Comment by r2international** [comment]
@AbhirajSharan  describe what did you done here as well as error in that

**Comment by AbhirajSharan** [comment]
@r2international closed #73
