### ISSUE TITLE
While creating Employee Details Personal Email Field Not Present but showing Details Page.

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#76]
![personnalemailnot present](https://cloud.githubusercontent.com/assets/7089705/3839650/e09fa4a0-1e13-11e4-8e7b-27b503a74361.png)

**Comment by r2international** [comment]
this section is removed

**Comment by AbhirajSharan** [comment]
Official Details Section has been removed ,so we can Close this issue
