### ISSUE TITLE
leave request should go through the same controller

### ISSUE THREAD

**Issue by r2international** [rameshbolla/LTMS#80]
we have multiple codes to apply a leave, any way applying leave is common functionality should go through single path(codes)

AddLeaveRequest(employee module)
AddAdminLeaveRequest(admin module)

same issue here #98

**Comment by r2international** [comment]
finally going to common functionality :+1:

**Comment by r2international** [comment]
finally going to common functionality :+1:

**Comment by AbhirajSharan** [comment]
@r2international  :Closed #80
