### ISSUE TITLE
Admin Lateness Edit 

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#84]
Admin Lateness edit should show the reason field as well as Employee Field should be disabled with the name
![adminlatenesseditdetails](https://cloud.githubusercontent.com/assets/7089705/3841682/6fcf2d06-1e2f-11e4-84ab-2130f241a8c7.png)

**Comment by r2international** [comment]
@AbhirajSharan  admin will not know the reason, reason only updated by employee OR hr team.

If admin need to edit lateness, for what ? may be to adjust lateness timing nothing else to do :+1:

**Comment by r2international** [comment]
this one will change soon..

**Comment by r2international** [comment]
@AbhirajSharan  admin will never knowing reasons of other people lateness thats only available to management, how  he will know ?

updated according to latest requirement

**Comment by AbhirajSharan** [comment]
@r2international  closed #84
