### ISSUE TITLE
User Account is not sending the Invitation on particular mail Id

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#87]
User Account is not sending the Invitation on particular mail Id also showing success message without showing the particular records in that list

![useraccountinvitation](https://cloud.githubusercontent.com/assets/7089705/3842163/eb3a7eaa-1e34-11e4-8d9f-90c2d8c64227.png)

**Comment by r2international** [comment]
@AbhirajSharan  that is autoselect, shows employees whose don't have user accounts. Once you select the employee name from auto select it will automatically fills username, firstname, lastname.

test in this way, if any issue raise another bug :+1:

**Comment by AbhirajSharan** [comment]
Invalid Bug
