### ISSUE TITLE
firbug error, employee module

### ISSUE THREAD

**Issue by r2international** [rameshbolla/LTMS#9]
![label2](https://cloud.githubusercontent.com/assets/4068693/3778472/a4632236-1973-11e4-92a2-db8026dd7c2d.png)

**Comment by AbhirajSharan** [comment]
@r2international  In fire Fox as well as In Google Chrome List of Applied Leaves not showing.
![employeeapplyleavefirefoxerror](https://cloud.githubusercontent.com/assets/7089705/3873530/e6691804-2132-11e4-84d5-6da79a3a7c1f.png)

**Comment by AbhirajSharan** [comment]
@r2international :Closed
