### ISSUE TITLE
When we try to refresh the Content In Fire Fox Data is invisible for certain time

### ISSUE THREAD

**Issue by AbhirajSharan** [rameshbolla/LTMS#99]
Compatibility issue(Fire Fox)
![datamissingwhenrefresh](https://cloud.githubusercontent.com/assets/7089705/3857235/5fc109fc-1f01-11e4-8f73-8cb3f007c0f2.png)

**Comment by AbhirajSharan** [comment]
with reference #99  finding it in many places

**Comment by r2international** [comment]
@AbhirajSharan  how to reproduce this bug, i check in firefox and chrome working fine.

**Comment by AbhirajSharan** [comment]
@r2international  : In previous version of production when we try to refresh the page it was showing this bug in fire fox but I think now it is working fine .So we can close this bug
